name: seller_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  fancy_drawer: ^2.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  lottie: ^3.1.2
  percent_indicator: ^4.2.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
